# Site settings
title: Krystle Barnes
header-img: img/home-bg.png
email: krystlecbarnes@gmail.com
copyright_name: krystlebarnes
description: > # this means to ignore newlines until "baseurl:"
  blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: krystlecbarnes
github_username:  krystlebarnes
learn_profile: krystlebarnes
email_username: krystlecbarnes@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
