# Site settings
author: Krystle Barnes
title: Krystle Barnes
header-img: img/home-bg.png
email: krystlecbarnes@gmail.com
copyright_name: Krystle Barnes
description: > # this means to ignore newlines until "baseurl:"
  blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  krystlebarnes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
